package coeficientesGrl_1;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antonio2
 */
public class CreacionInputs {


    public void Crearlos(double N, double bondlength, double baselength)
    {
        int x=0;
        int i;
        double distancia;
        WriteArch ManejoArchivosCrearlos = new WriteArch();
        
        
         for (i=1;i<=N;i=i+1)

        
            {
                ManejoArchivosCrearlos.CrearArchivo("energiahcl"+x);
                
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "title \"computation of mi molecula\"");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "start energiahcl"+x);
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "echo");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "charge 0");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "geometry units angstroms noautoz");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
               
               // ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "    H                    0.00000000     0.00000000     "+ distancia);
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "\n");
                ManejoArchivosCrearlos.EscribeDeNuevo("energiahcl"+x, "    Cl                   0.00000000     0.00000000    -0.20698824");
                
                
                
                x = x + 1;
            }
       
        
    }
    
    public void CrearlosDeCodigo(String archivonuevo,String ruta, int FrameInicial, int FrameFinal)
    {
        WriteArch ManejoArchivos = new WriteArch();
        int i;
        
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"#!/usr/local/bin/vmd");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"# VMD script written by save_state $Revision: 1.44 $");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"# VMD version: 1.9.1");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"set viewplist {}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"set fixedlist {}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"proc vmdrestoremymaterials {} {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  set mlist { Opaque Transparent BrushedMetal Diffuse Ghost Glass1 Glass2 Glass3 Glossy HardPlastic MetallicPastel Steel Translucent Edgy EdgyShiny EdgyGlass Goodsell AOShiny AOChalky AOEdgy BlownGlass GlassBubble }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  set mymlist [material list]");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  foreach mat $mlist {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    if { [lsearch $mymlist $mat] == -1 } { ");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"      material add $mat");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Opaque 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Opaque 0.650000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Opaque 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Opaque 0.534020");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Opaque 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Opaque 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Opaque 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Opaque 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Transparent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Transparent 0.650000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Transparent 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Transparent 0.534020");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Transparent 0.300000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Transparent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Transparent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Transparent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient BrushedMetal 0.080000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse BrushedMetal 0.390000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular BrushedMetal 0.340000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess BrushedMetal 0.150000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity BrushedMetal 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline BrushedMetal 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth BrushedMetal 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode BrushedMetal 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Diffuse 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Diffuse 0.620000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Diffuse 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Diffuse 0.530000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Diffuse 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Diffuse 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Diffuse 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Diffuse 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Ghost 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Ghost 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Ghost 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Ghost 0.230000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Ghost 0.100000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Ghost 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Ghost 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Ghost 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Glass1 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Glass1 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Glass1 0.650000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Glass1 0.530000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Glass1 0.150000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Glass1 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Glass1 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Glass1 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Glass2 0.520000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Glass2 0.760000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Glass2 0.220000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Glass2 0.590000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Glass2 0.680000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Glass2 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Glass2 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Glass2 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Glass3 0.150000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Glass3 0.250000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Glass3 0.750000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Glass3 0.800000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Glass3 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Glass3 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Glass3 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Glass3 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Glossy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Glossy 0.650000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Glossy 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Glossy 0.880000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Glossy 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Glossy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Glossy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Glossy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient HardPlastic 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse HardPlastic 0.560000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular HardPlastic 0.280000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess HardPlastic 0.690000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity HardPlastic 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline HardPlastic 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth HardPlastic 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode HardPlastic 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient MetallicPastel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse MetallicPastel 0.260000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular MetallicPastel 0.550000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess MetallicPastel 0.190000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity MetallicPastel 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline MetallicPastel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth MetallicPastel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode MetallicPastel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Steel 0.250000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Steel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Steel 0.380000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Steel 0.320000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Steel 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Steel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Steel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Steel 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Translucent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Translucent 0.700000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Translucent 0.600000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Translucent 0.300000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Translucent 0.800000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Translucent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Translucent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Translucent 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Edgy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Edgy 0.660000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Edgy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Edgy 0.750000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Edgy 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Edgy 0.620000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Edgy 0.940000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Edgy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient EdgyShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse EdgyShiny 0.660000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular EdgyShiny 0.960000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess EdgyShiny 0.750000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity EdgyShiny 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline EdgyShiny 0.760000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth EdgyShiny 0.940000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode EdgyShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient EdgyGlass 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse EdgyGlass 0.660000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular EdgyGlass 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess EdgyGlass 0.750000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity EdgyGlass 0.620000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline EdgyGlass 0.620000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth EdgyGlass 0.940000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode EdgyGlass 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient Goodsell 0.520000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse Goodsell 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular Goodsell 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess Goodsell 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity Goodsell 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline Goodsell 4.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth Goodsell 0.900000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode Goodsell 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient AOShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse AOShiny 0.850000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular AOShiny 0.200000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess AOShiny 0.530000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity AOShiny 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline AOShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth AOShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode AOShiny 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient AOChalky 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse AOChalky 0.850000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular AOChalky 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess AOChalky 0.530000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity AOChalky 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline AOChalky 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth AOChalky 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode AOChalky 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient AOEdgy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse AOEdgy 0.900000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular AOEdgy 0.200000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess AOEdgy 0.530000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity AOEdgy 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline AOEdgy 0.620000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth AOEdgy 0.930000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode AOEdgy 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient BlownGlass 0.040000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse BlownGlass 0.340000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular BlownGlass 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess BlownGlass 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity BlownGlass 0.100000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline BlownGlass 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth BlownGlass 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode BlownGlass 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change ambient GlassBubble 0.250000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change diffuse GlassBubble 0.340000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change specular GlassBubble 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change shininess GlassBubble 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change opacity GlassBubble 0.040000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outline GlassBubble 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change outlinewidth GlassBubble 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  material change transmode GlassBubble 1.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"vmdrestoremymaterials");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"# Atom selection macros");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro at {resname ADE A THY T");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro acidic {resname ASP GLU");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro cyclic {resname HIS PHE PRO TRP TYR");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro acyclic {protein and not cyclic");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro aliphatic {resname ALA GLY ILE LEU VAL");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro alpha {protein and name CA");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro amino {protein");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro aromatic {resname HIS PHE TRP TYR");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro basic {resname ARG HIS LYS HSP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro bonded {numbonds > 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro buried {resname ALA LEU VAL ILE PHE CYS MET TRP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro cg {resname CYT C GUA G");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro charged {basic or acidic");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro hetero {not (protein or nucleic)");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro hydrophobic {resname ALA LEU VAL ILE PRO PHE MET TRP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro small {resname ALA GLY SER");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro medium {resname VAL THR ASP ASN PRO CYS ASX PCA HYP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro large {protein and not (small or medium)");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro neutral {resname VAL PHE GLN TYR HIS CYS MET TRP ASX GLX PCA HYP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro polar {protein and not hydrophobic");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro purine {resname ADE A GUA G");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro pyrimidine {resname CYT C THY T URA U");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro surface {protein and not buried");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro lipid {resname DLPE DMPC DPPC GPC LPPC PALM PC PGCL POPC POPE");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro lipids {lipid");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro ion {resname AL BA CA CAL CD CES CLA CL CO CS CU CU1 CUA HG IN IOD K MG MN3 MO3 MO4 MO5 MO6 NA NAW OC7 PB POT PT RB SOD TB TL WO4 YB ZN ZN1 ZN2");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro ions {ion");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro sugar {resname AGLC");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro solvent {not (protein or sugar or nucleic or lipid)");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro carbon {name \"C.*\" and not ion");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro hydrogen {name \"[0-9]?H.*\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro nitrogen {name \"N.*\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro oxygen {name \"O.*\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro sulfur {name \"S.*\" and not ion");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro noh {not hydrogen");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro heme {resname HEM HEME");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationall {altloc \"\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationA {altloc \"\" or altloc \"A\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationB {altloc \"\" or altloc \"B\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationC {altloc \"\" or altloc \"C\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationD {altloc \"\" or altloc \"D\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationE {altloc \"\" or altloc \"E\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro conformationF {altloc \"\" or altloc \"F\"");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro drude {type DRUD or type LP");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro unparametrized beta<1");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"atomselect macro addedmolefacture {occupancy 0.8}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"# Display settings");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display eyesep       0.065000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display focallength  2.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display height       6.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display distance     -2.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display projection   Perspective");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display nearclip set 0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display farclip  set 10.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display depthcue   on");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display cuestart   0.500000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display cueend     10.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display cuedensity 0.320000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"display cuemode    Exp2");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol new " + ruta + "/ArchivosSalida/ArchivosCUBO/PruebaFrame"+FrameInicial+"ESP.cube type cube first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");

        
        for(i=(FrameInicial + 1); i<= FrameFinal; i++)
        {
            ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol addfile " + ruta + "/ArchivosSalida/ArchivosCUBO/PruebaFrame"+i+"ESP.cube type cube first 0 last -1 step 1 filebonds 1 autobonds 1 waitfor all");
            ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        }







        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol delrep 0 top");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol representation Surf 1.400000 0.000000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol color Volume 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol selection {all}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol material Opaque");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol addrep top");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol selupdate 0 top 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol colupdate 0 top 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol scaleminmax top 0 -0.070000 0.070000");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol smoothrep top 0 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol drawframes top 0 {now}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 0 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  0 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 0 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 0 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 1 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  1 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 1 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 1 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 2 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  2 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 2 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 2 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 3 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  3 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 3 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 3 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 4 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  4 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 4 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 4 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane center 5 0 top {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane color  5 0 top {0.5 0.5 0.5 }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane normal 5 0 top {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol clipplane status 5 0 top {0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol rename top PruebaFrame73ESP.cube");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"set viewpoints([molinfo top]) {{{1 0 0 0.948171} {0 1 0 -1.40054} {0 0 1 0.00273297} {0 0 0 1}} {{0.925461 -0.377423 -0.0330015 0} {-0.199588 -0.559729 0.804295 0} {-0.322027 -0.737747 -0.593334 0} {0 0 0 1}} {{0.112473 0 0 0} {0 0.112473 0 0} {0 0 0.112473 0} {0 0 0 1}} {{1 0 0 0} {0 1 0 0} {0 0 1 0} {0 0 0 1}}}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"lappend viewplist [molinfo top]");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"set topmol [molinfo top]");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"# done with molecule 0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"foreach v $viewplist {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  molinfo $v set {center_matrix rotate_matrix scale_matrix global_matrix} $viewpoints($v)");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"foreach v $fixedlist {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  molinfo $v set fixed 1");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"unset viewplist");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"unset fixedlist");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"mol top $topmol");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"unset topmol");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"proc vmdrestoremycolors {} {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors RWB {1.0 0.0 0.0} {1.0 1.0 1.0} {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors BWR {0.0 0.0 1.0} {1.0 1.0 1.0} {1.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors RGryB {1.0 0.0 0.0} {0.5 0.5 0.5} {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors BGryR {0.0 0.0 1.0} {0.5 0.5 0.5} {1.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors RGB {1.0 0.0 0.0} {0.0 1.0 0.0} {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors BGR {0.0 0.0 1.0} {0.0 1.0 0.0} {1.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors RWG {1.0 0.0 0.0} {1.0 1.0 1.0} {0.0 1.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors GWR {0.0 1.0 0.0} {1.0 1.0 1.0} {1.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors GWB {0.0 1.0 0.0} {1.0 1.0 1.0} {0.0 0.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors BWG {0.0 0.0 1.0} {1.0 1.0 1.0} {0.0 1.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors BlkW {0.0 0.0 0.0} {0.5 0.5 0.5} {1.0 1.0 1.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"color scale colors WBlk {1.0 1.0 1.0} {0.5 0.5 0.5} {0.0 0.0 0.0}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color scale method RWB");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  set colorcmds {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Display {BackgroundTop} black}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Display {BackgroundBot} blue2}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Display {FPS} white}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Name {LPA} green}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Name {LPB} green}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Type {LP} green}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Type {DRUD} pink}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {X} cyan}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ac} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ag} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Al} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Am} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ar} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {As} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {At} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Au} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {B} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ba} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Be} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Bh} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Bi} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Bk} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Br} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ca} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cd} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ce} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cf} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cl} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cm} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Co} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cs} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Cu} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Db} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ds} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Dy} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Er} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Es} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Eu} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {F} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Fe} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Fm} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Fr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ga} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Gd} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ge} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {He} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Hf} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Hg} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ho} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Hs} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {I} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {In} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ir} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {K} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Kr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {La} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Li} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Lr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Lu} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Md} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Mg} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Mn} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Mo} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Mt} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Na} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Nb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Nd} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ne} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ni} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {No} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Np} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Os} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pa} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pd} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pm} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Po} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pt} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Pu} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ra} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Rb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Re} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Rf} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Rg} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Rh} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Rn} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ru} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sc} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Se} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sg} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Si} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sm} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sn} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Sr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ta} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Tb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Tc} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Te} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Th} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Ti} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Tl} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Tm} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {U} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {V} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {W} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Xe} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Y} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Yb} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Element {Zr} ochre}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Resname {} silver}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Chain {X} blue}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Segname {} blue}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Conformation {all} blue}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Molecule {0} blue}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Structure {3_10_Helix} blue}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Surface {Grasp} gray}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Labels {Springs} orange}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Stage {Even} gray}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    {color Stage {Odd} silver}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  foreach colcmd $colorcmds {");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"    set val [catch {eval $colcmd}]");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  }");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 0 0.0 0.0 1.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 2 0.3499999940395355 0.3499999940395355 0.3499999940395355");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 3 1.0 0.5 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 4 1.0 1.0 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 5 0.5 0.5 0.20000000298023224");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 6 0.6000000238418579 0.6000000238418579 0.6000000238418579");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 7 0.0 1.0 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 9 1.0 0.6000000238418579 0.6000000238418579");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 11 0.6499999761581421 0.0 0.6499999761581421");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 12 0.5 0.8999999761581421 0.4000000059604645");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 13 0.8999999761581421 0.4000000059604645 0.699999988079071");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 14 0.5 0.30000001192092896 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 15 0.5 0.5 0.75");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 17 0.8799999952316284 0.9700000286102295 0.019999999552965164");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 18 0.550000011920929 0.8999999761581421 0.019999999552965164");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 19 0.0 0.8999999761581421 0.03999999910593033");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 20 0.0 0.8999999761581421 0.5");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 21 0.0 0.8799999952316284 1.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 22 0.0 0.7599999904632568 1.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 23 0.019999999552965164 0.3799999952316284 0.6700000166893005");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 24 0.009999999776482582 0.03999999910593033 0.9300000071525574");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 25 0.27000001072883606 0.0 0.9800000190734863");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 26 0.44999998807907104 0.0 0.8999999761581421");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 27 0.8999999761581421 0.0 0.8999999761581421");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 28 1.0 0.0 0.6600000262260437");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 29 0.9800000190734863 0.0 0.23000000417232513");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 30 0.8100000023841858 0.0 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 31 0.8899999856948853 0.3499999940395355 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"  color change rgb 32 0.9599999785423279 0.7200000286102295 0.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"}");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"vmdrestoremycolors");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"label textsize 1.0");
        ManejoArchivos.EscribeDeNuevo(archivonuevo,"\n");
 
    }
    
    
    
        public void CrearImputsGaussian(String ArchivoXYZ, String archivonuevo, String ruta)
    {
        
        int LineaPrimerComentario;
        int LineaSegundoComentario;
        int IntervaloEntreComentarios;
        int LineaUltimoComentario;
        int ContadorLineaXYZ;
        String LineaACopiar;
        int frame;
        int i;
        
        WriteArch AnalizarArchivoXYZ = new WriteArch();
        WriteArch ManejoArchivo = new WriteArch();
        CopiarArchivo ManejoCopiar = new CopiarArchivo();
        
        //primero ver el intervalo en que se encuentran los comentarios entre los datos de coordenadas
        LineaPrimerComentario = AnalizarArchivoXYZ.BuscarYdarNumLineaDeLineaAaB(ruta + "/ArchivosRequeridos/" + ArchivoXYZ, "molec", 1, 50000);
        //se eligio 1000 sabiendo que no se trabaja con un archivo de mas de 1000 atomos distintos
        LineaSegundoComentario = AnalizarArchivoXYZ.BuscarYdarNumLineaDeLineaAaB(ruta + "/ArchivosRequeridos/" + ArchivoXYZ, "molec", LineaPrimerComentario+1, 50000);
        LineaUltimoComentario = AnalizarArchivoXYZ.BuscarYdarLineaUltimaPalabraDeLineaAaB(ruta + "/ArchivosRequeridos/" + ArchivoXYZ, "molec", 1, 50000);
        
        // ruta + "/ArchivosRequeridos/" + ArchivoXYZ
        IntervaloEntreComentarios = LineaSegundoComentario - LineaPrimerComentario;
        int CantidadLineasCoordenadas = IntervaloEntreComentarios -2;
        
         frame = 1;
         ContadorLineaXYZ = LineaPrimerComentario;
         while (ContadorLineaXYZ <= LineaUltimoComentario)
            {
                ManejoArchivo.CrearArchivo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "%chk="+ ruta + "/ArchivosSalida/ArchivosCHK/" +"PruebaFrame"+frame+".chk");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "# hf/3-21g Pop=All");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "Prueba Frame "+ frame);
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "0 1");
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                
                for(i = ContadorLineaXYZ + 1; i <= CantidadLineasCoordenadas + ContadorLineaXYZ; i++)
                {
                    LineaACopiar = ManejoCopiar.CopiarLineaIndicada(ruta + "/ArchivosRequeridos/" + ArchivoXYZ, i);
                    ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", LineaACopiar);
                    ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                    
                }
                
                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".input", "\n");
                
                ContadorLineaXYZ = ContadorLineaXYZ + IntervaloEntreComentarios;
                frame = frame + 1;
            
               
            }
         
         
       
        
    }
        
        
//        
//          public void CrearXYZ(String SalidaColision, String ArchivoXYZ, String ruta)
//    {
//        
//        int LineaPrimerComentario;
//        int LineaSegundoComentario;
//        int IntervaloEntreComentarios;
//        int LineaUltimoComentario;
//        int ContadorLineaXYZ;
//        String LineaACopiar;
//        int frame;
//        int i;
//        
//        WriteArch AnalizarArchivoXYZ = new WriteArch();
//        WriteArch ManejoArchivo = new WriteArch();
//        CopiarArchivo ManejoCopiar = new CopiarArchivo();
//        
//        //primero ver el intervalo en que se encuentran los comentarios entre los datos de coordenadas
//        LineaPrimerComentario = AnalizarArchivoXYZ.BuscarYdarNumLineaDeLineaAaB(ruta + ArchivoXYZ, "molec", 1, 50000);
//        //se eligio 1000 sabiendo que no se trabaja con un archivo de mas de 1000 atomos distintos
//        LineaSegundoComentario = AnalizarArchivoXYZ.BuscarYdarNumLineaDeLineaAaB(ruta + ArchivoXYZ, "molec", LineaPrimerComentario+1, 50000);
//        LineaUltimoComentario = AnalizarArchivoXYZ.BuscarYdarLineaUltimaPalabraDeLineaAaB(ruta + ArchivoXYZ, "molec", 1, 50000);
//        
//        // ruta + "/ArchivosRequeridos/" + ArchivoXYZ
//        IntervaloEntreComentarios = LineaSegundoComentario - LineaPrimerComentario;
//        int CantidadLineasCoordenadas = IntervaloEntreComentarios -2;
//        
//        // ManejoArchivo.CrearArchivo(ruta + archivonuevo + frame + ".xyz");
//         frame = 1;
//         ContadorLineaXYZ = LineaPrimerComentario;
//         while (ContadorLineaXYZ <= LineaUltimoComentario)
          //  {
                
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "%chk="+ ruta + "/ArchivosSalida/ArchivosCHK/" +"PruebaFrame"+frame+".chk");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "# hf/3-21g Pop=All");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "Prueba Frame "+ frame);
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "0 1");
//                ManejoArchivo.EscribeDeNuevo(ruta + archivonuevo + frame + ".xyz", "\n");
//                
//                for(i = ContadorLineaXYZ + 1; i <= CantidadLineasCoordenadas + ContadorLineaXYZ; i++)
//                {
//                    LineaACopiar = ManejoCopiar.CopiarLineaIndicada(ruta + "/ArchivosRequeridos/" + ArchivoXYZ, i);
//                    ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".xyz", LineaACopiar);
//                    ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".xyz", "\n");
//                    
//                }
//                
//                ManejoArchivo.EscribeDeNuevo(ruta + "/ArchivosSalida/InputsGaussian/" + archivonuevo + frame + ".xyz", "\n");
//                
//                ContadorLineaXYZ = ContadorLineaXYZ + IntervaloEntreComentarios;
//                frame = frame + 1;
//            
//               
//            }
//    

    
    
    
}
